AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
  SuggestExtensions: false

require: []

plugins:
  - rubocop-rails
  - rubocop-rspec

Layout/LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'config/environments/*.rb'

Metrics/AbcSize:
  Max: 20

Rails/ThreeStateBooleanColumn:
  Exclude:
    - 'db/migrate/20250211195223_create_users.rb'
    - 'db/migrate/20250211195738_create_user_settings.rb'
    - 'db/migrate/20250215150002_create_schedules.rb'
    - 'db/migrate/20250216175748_create_notification_logs.rb'
